# Makefile for Tiny Calculator using Flex and Bison

# Compiler and Flags
CXX = g++
CXXFLAGS = -std=c++11 -lm

# Targets and File Names
LEX = flex
YACC = bison
LEX_SRC = calc.l
YACC_SRC = calc.y
LEX_OUT = lex.yy.cpp
YACC_OUT = calc.tab.cpp
YACC_HEADER = calc.tab.h
TARGET = calc

# Default rule
all: $(TARGET)

$(TARGET): lex.yy.o calc.tab.o
	$(CXX) -o $(TARGET) lex.yy.o calc.tab.o -lstdc++ -lm

lex.yy.o: $(LEX_OUT)
	$(CXX) -c $(LEX_OUT) -o $@ $(CXXFLAGS)

calc.tab.o: $(YACC_OUT)
	$(CXX) -c $(YACC_OUT) -o $@ $(CXXFLAGS)

$(LEX_OUT): $(LEX_SRC) $(YACC_HEADER)
	$(LEX) $(LEX_SRC)
	mv lex.yy.c lex.yy.cpp

$(YACC_OUT): $(YACC_SRC)
	$(YACC) -d -t -v $(YACC_SRC)
	mv calc.tab.c calc.tab.cpp

clean:
	rm -f *.o $(TARGET) lex.yy.cpp calc.tab.cpp calc.tab.h calc.output
